name = "fitzone-gym"
main = "worker/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "fitzone-db"
database_id = "f9eccbcf-0493-4312-9736-5464e4c73471"

[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGIN = "https://your-domain.com"
